# Generated by Django 5.2.5 on 2025-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('atomicnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('atomicMass', models.CharField(max_length=20)),
                ('cpkHexColor', models.CharField(max_length=7)),
                ('electronicConfiguration', models.CharField(max_length=100)),
                ('electronegativity', models.FloatField()),
                ('atomicRadius', models.FloatField()),
                ('ionRadius', models.CharField(max_length=20)),
                ('vanDelWaalsRadius', models.FloatField()),
                ('ionizationEnergy', models.FloatField()),
                ('electronAffinity', models.FloatField()),
                ('oxidationStates', models.CharField(max_length=50)),
                ('standardState', models.CharField(max_length=20)),
                ('bondingType', models.CharField(max_length=20)),
                ('meltingPoint', models.FloatField()),
                ('boilingPoint', models.FloatField()),
                ('density', models.FloatField()),
                ('groupBlock', models.CharField(max_length=20)),
                ('yearDiscovered', models.IntegerField()),
            ],
        ),
    ]
