# Generated by Django 5.2.5 on 2025-08-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='atomicMass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='atomicRadius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='boilingPoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='bondingType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cpkHexColor',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='electronAffinity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='electronegativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='electronicConfiguration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='groupBlock',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='ionRadius',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='ionizationEnergy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='meltingPoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='oxidationStates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='standardState',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='vanDelWaalsRadius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='yearDiscovered',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
