# Generated by Django 5.2.5 on 2025-08-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0002_alter_elemento_atomicmass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='groupBlock',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
