# Generated by Django 5.2.5 on 2025-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0003_alter_elemento_groupblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_Element',
            fields=[
                ('atomicnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('atomicMass', models.CharField(blank=True, max_length=20, null=True)),
                ('groupBlock', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
